{{- $servicePort := .Values.service.port -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "prisma.fullname" . }}
  labels:
    app: {{ template "prisma.name" . }}
    chart: {{ template "prisma.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  protocol: "http"
  server: {{ template "prisma.fullname" . }}  
  port: "{{ $servicePort }}"
  # TODO config in a secret as it contains a secret
  config: |
    port: {{ .Values.service.port }}
    {{- if .Values.service.secret }}
    managementApiSecret: {{ .Values.service.secret }}
    {{- end}}
    databases:
      default:
        connector: {{ .Values.database.connector }}
        host: {{ template "prisma.database.host" . }}
        port: {{ template "prisma.database.port" . }}
        database: {{ template "prisma.database.name" . }}
        user: {{ .Values.database.user }}
        password: {{ .Values.database.password }}
        migrations: true
